// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @notice Interface for Groth16 ZK proof verification
 * @dev Generated by snarkjs from Groth16 ceremony
 */
interface IVerifier {
    /**
     * @notice Verify a Groth16 proof
     * @param _pA Proof point A in G1
     * @param _pB Proof point B in G2
     * @param _pC Proof point C in G1
     * @param _pubSignals Public signals (inputs to the circuit)
     * @return True if proof is valid
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[] calldata _pubSignals
    ) external view returns (bool);
}
